# Write your MySQL query statement below
WITH student_subject AS (
    SELECT stu.student_id, stu.student_name, sub.subject_name
    FROM Students AS stu CROSS JOIN Subjects AS sub
)

SELECT student_id, student_name, subject_name, SUM(attended) AS attended_exams
FROM (
    SELECT ss.student_id, ss.student_name, ss.subject_name,
    CASE
        WHEN ex.subject_name IS NULL THEN 0
        ELSE 1
        END AS attended
    FROM student_subject AS ss LEFT JOIN Examinations AS ex
    ON ss.student_id = ex.student_id AND ss.subject_name = ex.subject_name
) AS student_exams
GROUP BY student_id, student_name, subject_name
ORDER BY student_id, subject_name

-- Optimizations
-- Avoid the Nested CTE: Rather than using a CROSS JOIN followed by a LEFT JOIN,
-- we can simplify the query by using an outer join between Students and Subjects
-- with Examinations. This way, we eliminate the need for student_subject and reduce
-- the number of rows generated by the CROSS JOIN.

-- Directly Calculate Attendance: Instead of generating a 0/1 flag for attendance in the
-- nested CTE and then summing it, we can do this directly with a COUNT and conditional
-- aggregation to check if an exam was attended.